USE [Vmob_lgm695_Core]
GO

SELECT 
OFFER.ID as Offer_Id,
[dbo].[ExtendedDataTemplate].[Name] as Offer_Type
 FROM OFFER
LEFT JOIN [dbo].[ExtendedDataTemplate]
ON OFFER.[ExtendedDataTemplateId] = [dbo].[ExtendedDataTemplate].Id

SELECT * FROM [dbo].[ExtendedDataTemplate]

select top 100 redemptioncountunlimited from offer
select * from offer where id = 2325
SELECT [Id]
      ,[CampaignId]
      ,[OrganisationId]
      ,[CategoryId]
      ,[Title]
      ,[Description]
      ,[WhenStarts]
      ,[WhenExpires]
      ,[TermsAndConditions]
      ,[WhenLastUpdated]
      ,[HasBarcodeImage]
      ,[RedemptionLimit]
      ,[RedemptionText]
      ,[PaymentType]
      ,[ChargeModel]
      ,[ChargeAmount]
      ,[ChargeBudgetMax]
      ,[ChargeBudgetUnlimited]
      ,[RedemptionCountUnlimited]
      ,[CodeType]
      ,[PremiumPlacement]
      ,[PremiumPlacementBudgetMax]
      ,[DiscountPercent]
      ,[DiscountValue]
      ,[OfferStatus]
      ,[PremiumPlacementPrice]
      ,[AlternativeTitle]
      ,[AlternativeDescription]
      ,[AlternativeTermsAndConditions]
      ,[PaymentProviderId]
      ,[PaymentAmount]
      ,[PaymentTaxRate]
      ,[Margin]
      ,[SMSCodes]
      ,[ApplyGeoFenceFilters]
      ,[PromoImagePath]
      ,[ExtendedData]
      ,[DailyStartTime]
      ,[DailyEndTime]
      ,[DaysOfWeek]
      ,[BaseWeight]
      ,[NoCompeteGroup]
      ,[IsGiftable]
      ,[InStoreRedemptions]
      ,[AverageTrayValue]
      ,[AverageDiscount]
      ,[IsReward]
      ,[AltImagePath]
      ,[ContentUrl]
      ,[IsRespawning]
      ,[RespawnsInDays]
      ,[EnableDistanceWeight]
      ,[ApplyBeaconFilter]
      ,[IsAvailableAllStores]
      ,[AlternativePromoImagePath]
      ,[AlternativeAltImagePath]
      ,[PredefinedCodesLastUpdatedUTC]
      ,[ExtendedDataTemplateId]
      ,[PromotionalImageDescription]
      ,[AlternativePromotionalImageDescription]
      ,[AltImageDescription]
      ,[AlternativeAltImageDescription]
      ,[ExtendedDataDynamicFields]
      ,[Limit]
      ,[CodeExpiryInMinutes]
      ,[CDNVersion]
      ,[RedemptionPrefixCode]
  FROM [dbo].[Offer]
GO


